FROM alpine:latest AS builder

ARG SCCACHE_VERSION v0.5.4

RUN <<EOF
#!/usr/bin/env sh

set -eux

apk add --update --no-cache wget

wget https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz

tar xvf sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz
mv sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/sccache /usr/bin/sccache

EOF

FROM gcr.io/distroless/static-debian11:latest AS sccache

COPY --from=builder /usr/bin/sccache /usr/bin/sccache

ENTRYPOINT ["/usr/bin/sccache", "--version"]
